name: CI

on:
  push:
    branches: [ 'master' ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LINGDOCS_NPM_TOKEN: ${{ secrets.LINGDOCS_NPM_TOKEN }}
      LINGDOCS_DICTIONARY_URL: ${{ secrets.LINGDOCS_DICTIONARY_URL }}
      ALGOLIA_GRAMMAR_API_KEY: ${{ secrets.ALGOLIA_GRAMMAR_API_KEY }} 
      ALGOLIA_GRAMMAR_APP_ID: ${{ secrets.ALGOLIA_GRAMMAR_APP_ID }}
      ALGOLIA_GRAMMAR_INDEX: ${{ secrets.ALGOLIA_GRAMMAR_INDEX }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm install --force && \
          npm run get-words && \
          # npx playwright install --with-deps && \
          # npm run test && \
          npm run build && \
          npx netlify deploy --prod --site $NETLIFY_SITE_ID
